from machine import Pin
from time import sleep

groveled = Pin(18, Pin.OUT)
led = Pin(25, Pin.OUT)
ml1 = Pin(13, Pin.OUT)
ml2 = Pin(12, Pin.OUT)
mr1 = Pin(11, Pin.OUT)
mr2 = Pin(10, Pin.OUT)

while True:
    groveled.high()
    led.low()
    ml1.high()
    ml2.low()
    mr1.high()
    mr2.low()
    sleep(3)
    led.low()
    groveled.low()
    mr1.low()
    mr2.low()
    ml1.low()
    ml2.low()
    sleep(3)
    led.high()
    ml1.low()
    ml2.high()
    mr1.low()
    mr1.high()
    sleep(3)
    led.low()
    groveled.low()
    ml1.high()
    ml2.high()
    mr1.high()
    mr2.high()
    sleep(3)

